version: '3.8'

services:
  # Service PHP-FPM (ton Dockerfile)
  app:
    build: 
      context: .
      target: base # En local, on peut s'arrêter à l'étape base
    container_name: laravel-app
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  # Service Nginx
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Note le chemin ici
    depends_on:
      - app
    networks:
      - laravel-network

  # Service MySQL
  mysql:
    image: mysql:8.0 
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql_data:
